config/routes.rb
Rails.application.routes.draw do

  root to: 'jobs#index'

  resources :jobs, except: [:show] do
    get :applicants

    collection do
      get :skills_list
    end
  end

  resources :applicants, except: [:show] do
    get :jobs

    collection do
      get :skills_list
    end
  end
end

app/models/applicant.rb
require 'pry'

class Applicant < ActiveRecord::Base
  include Skillable

  enum status: [ :active, :inactive ]

  validates :name, :contact, :status, :desired_salary,
    presence: true

  validates :name, format: {
    with: /\A[а-яА-Яё]+\s[а-яА-Яё]+\s[а-яА-Яё]+\z/
  }

  validates :desired_salary, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }

  validate do
    unless contact =~ AuxRegexp::EMAIL_REGEXP ||
      contact =~ AuxRegexp::PHONE_REGEXP

      errors.add :contact, :email_or_phone
    end
  end

  scope :active, -> { where(status: 0) }
  scope :inactive, -> { where(status: 1) }

  def full_match_jobs
    Job.where('ARRAY[?]::varchar[] @> skills', skills)
  end

  def partially_match_jobs
    Job.where('ARRAY[?]::varchar[] && skills', skills).
      where.not('ARRAY[?]::varchar[] <@ skills', skills)
  end
end

app/models/concerns/skillable.rb
module Skillable
  extend ActiveSupport::Concern

  included do
    validates :skills, presence: true
  end

  module ClassMethods
    def distinct_skills(term = "")
      ActiveRecord::Base.connection.execute("SELECT DISTINCT unnest(skills) as skill FROM #{table_name}").
        to_a.map{ |o| o['skill'] }.
        find_all{ |o|
          if term.present?
            o.downcase.include?(term.downcase)
          else
            true
          end
        }
    end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Skillable

  validates :name, :issue_date, :valid_time, :salary,
    :skills, :contact, presence: true

  validates :issue_date, date: {
    before_or_equal_to: proc { Date.today }
  }

  validates :valid_time, numericality: {
    only_integer: true, greater_than: 0
  }

  validates :salary, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }

  scope :actual, -> do
    where ':today <= ("issue_date" + "valid_time")',
      today: Date.today
  end

  scope :not_actual, -> do
    where ':today > ("issue_date" + "valid_time")',
      today: Date.today
  end

  def is_actual?
    (Date.today - (issue_date + valid_time)).to_i < 0
  end

  def full_match_applicants
    Applicant.where('ARRAY[?]::varchar[] <@ skills', skills)
  end

  def partially_match_applicants
    Applicant.where('ARRAY[?]::varchar[] && skills', skills).
      where.not('ARRAY[?]::varchar[] <@ skills', skills)
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  include SkillsList

  def index
    @applicants = Applicant.order('desired_salary ASC').all
  end

  def destroy
    applicant = Applicant.where(id: params[:id]).first
    applicant.destroy
    redirect_to action: :index
  end

  def jobs
    @applicant = Applicant.where(id: params[:applicant_id]).first

    if @applicant
      @full_match = @applicant.full_match_jobs.actual.
        order('salary DESC')
      @partially_match = @applicant.partially_match_jobs.
        actual.order('salary DESC')
    else
      status 404
    end
  end

  def new
    @applicant = Applicant.new
  end

  def create
    @applicant = Applicant.new(applicant_params)

    if @applicant.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    @applicant = Applicant.where(id: params[:id]).first.decorate

    unless @applicant
      render status: 404

    end
  end

  def update
    @applicant = Applicant.where(id: params[:id]).first.decorate

    if @applicant.update_attributes(applicant_params)
      redirect_to action: :index
    else
      render :edit
    end
  end
  
  private

  def applicant_params
    params.require(:applicant).permit(:name, :contact,
      :status, :desired_salary, :skills => [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/skills_list.rb
module SkillsList
  extend ActiveSupport::Concern

  included do
    def skills_list
      term = params[:q]

      render json: 
        (Applicant.distinct_skills(term) +
         Job.distinct_skills(term)).
        uniq.map{|skill| { id: skill, text: skill } }
    end
  end
end

app/controllers/jobs_controller.rb
require 'pry'

class JobsController < ApplicationController
  include SkillsList

  def index
    @jobs = Job.order('salary ASC').all
  end

  def destroy
    job = Job.where(id: params[:id]).first
    job.destroy
    redirect_to action: :index
  end

  def applicants
    @job = Job.where(id: params[:job_id]).first

    if @job
      @full_match = @job.full_match_applicants.active.
        order('desired_salary ASC')
      @partially_match = @job.partially_match_applicants.
        active.order('desired_salary ASC')
    else
      status 404
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    @job = Job.where(id: params[:id]).first.decorate

    unless @job
      render status: 404

    end
  end

  def update
    @job = Job.where(id: params[:id]).first.decorate

    if @job.update_attributes(job_params)
      redirect_to action: :index
    else
      render :edit
    end
  end
  
  private

  def job_params
    params.require(:job).permit(:name,
      :issue_date, :valid_time, :salary,
      :contact, :skills => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/applicants/_edit_form.slim
javascript:
  $(function() {
    $('#applicant_skills').select2({
      tags: true,
      ajax: {
        url: "#{ skills_list_applicants_url }",
        dataType: "json",
        processResults: function(data, page) {
          return { results: data }
        }
      },
      escapeMarkup: function (markup) { return markup; },
      minimumInputLength: 1,
      templateResult: function(data) { return data.text },
      templateSelection: function(data) { return data.text }
    });
  });

= simple_form_for applicant do |f|
  = f.input :name
  = f.input :skills, collection: applicant.skills,
    input_html: { multiple: true },
    include_hidden: false
  = f.input :status, collection: [:active, :inactive],
    include_blank: false
  = f.input :desired_salary
  = f.input :contact
  = f.button :submit

app/views/applicants/edit.slim
h3 Редактирование соискателя
= render partial: "applicants/edit_form",
  locals: { applicant: @applicant }

app/views/applicants/index.slim
p
  = link_to fa_icon('plus', text: 'Создать'),
    new_applicant_path,
    class: 'btn btn-primary'
- if @applicants.count > 0
  .list-group
    - @applicants.each do |applicant|
      .list-group-item
        .btn-group.pull-right
          = link_to fa_icon('briefcase', text: 'Вакансии'),
            applicant_jobs_path(applicant),
            class: 'btn btn-xs btn-default'
          = link_to fa_icon('edit'),
            edit_applicant_path(applicant),
            class: 'btn btn-xs btn-default'
          = link_to fa_icon('remove'),
            applicant_path(applicant),
            class: 'btn btn-xs btn-danger',
            method: 'delete',
            data: { confirm: 'Вы действительно хотите удалить соискателя?' }

        = render partial: 'shared/applicant',
          locals: { applicant: applicant }
- else
  .well
    | Нет записей соискателей

app/views/applicants/jobs.slim
p
  = link_to fa_icon('arrow-left', text: 'Назад к соискателям'), applicants_path

.well
  = render partial: 'shared/applicant',
    locals: { applicant: @applicant }

h3 Полное совпадение
- if @full_match.present?
  .list-group
    - @full_match.each do |job|
      .list-group-item
        = render partial: 'shared/job',
          locals: { job: job }
- else
  .well Полных совпадений нет

h3 Частичное совпадение
- if @partially_match.present?
  .list-group
    - @partially_match.each do |job|
      .list-group-item
        = render partial: 'shared/job',
          locals: { job: job }
- else
  .well Частичных совпадений нет

app/views/applicants/new.slim
h3 Создание соискателя
= render partial: "applicants/edit_form",
  locals: { applicant: @applicant }

app/views/jobs/_edit_form.slim
javascript:
  $(function() {
    $('#job_skills').select2({
      tags: true,
      ajax: {
        url: "#{ skills_list_jobs_url }",
        dataType: "json",
        processResults: function(data, page) {
          return { results: data }
        }
      },
      escapeMarkup: function (markup) { return markup; },
      minimumInputLength: 1,
      templateResult: function(data) { return data.text },
      templateSelection: function(data) { return data.text }
    });
  });

= simple_form_for job do |f|
  = f.input :name
  = f.input :skills, collection: job.skills,
    input_html: { multiple: true },
    include_hidden: false
  = f.input :issue_date, as: :date,
    start_year: Date.today.year - 10,
    end_year: Date.today.year,
    order: [:day, :month, :year]
  = f.input :valid_time
  = f.input :salary
  = f.input :contact
  = f.button :submit

app/views/jobs/applicants.slim
p
  = link_to fa_icon('arrow-left', text: 'Назад к вакинсиям'), root_path

.well
  = render partial: 'shared/job',
    locals: { job: @job }

h3 Полное совпадение
- if @full_match.present?
  .list-group
    - @full_match.each do |applicant|
      .list-group-item
        = render partial: 'shared/applicant',
          locals: { applicant: applicant }
- else
  .well Полных совпадений нет

h3 Частичное совпадение
- if @partially_match.present?
  .list-group
    - @partially_match.each do |applicant|
      .list-group-item
        = render partial: 'shared/applicant',
          locals: { applicant: applicant }
- else
  .well Частичных совпадений нет

app/views/jobs/edit.slim
h3 Редактирование вакансии
= render partial: "jobs/edit_form",
  locals: { job: @job }

app/views/jobs/index.slim
p
  = link_to fa_icon('plus', text: 'Создать'),
    new_job_path,
    class: 'btn btn-primary'
- if @jobs.count > 0
  .list-group
    - @jobs.each do |job|
      .list-group-item
        .btn-group.pull-right
          = link_to fa_icon('users', text: 'Кандидаты'),
            job_applicants_path(job),
            class: 'btn btn-xs btn-default'
          = link_to fa_icon('edit'),
            edit_job_path(job),
            class: 'btn btn-xs btn-default'
          = link_to fa_icon('remove'),
            job_path(job),
            class: 'btn btn-xs btn-danger',
            method: 'delete',
            data: { confirm: 'Вы действительно хотите удалить вакансию?' }

        = render partial: 'shared/job',
          locals: { job: job }

- else
  .well
    | Нет записей вакансий

app/views/jobs/new.slim
h3 Создание вакансии
= render partial: "jobs/edit_form",
  locals: { job: @job }

app/views/layouts/application.slim
doctype html
html
  head
    title Работа для тебя (ДЕМО)
    = stylesheet_link_tag 'application',
      media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application',
      'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-default
      .container
        .navbar-header
          a.navbar-brand Работа (ДЕМО)

    .container
      .row
        .col-md-3
          = render_navigation

        .col-md-9

          /- if notice.present?
            p.alert.alert-info = notice
          /- if alert.present?
            p.alert.alert-warning = alert

          = yield

app/views/shared/_applicant.slim
h4 = fa_icon 'user', text: applicant.name

div
  - if applicant.active?
    .label.label-success Активен
  - else
    .label.label-default Неактивен

.small
  b> Желаемая зароботная плата:
  = applicant.desired_salary

.small
  b>Контакты:
  = applicant.contact

div
  b>Навыки:
  - applicant.skills.each do |skill|
    .label.label-info> = skill

app/views/shared/_job.slim
h4 = fa_icon 'list-alt', text: job.name

div
  - if job.is_actual?
    .label.label-success Актуально
  - else
    .label.label-default Неактуально

.small
  b> Заработная плата:
  = job.salary

.small
  b> Добавлено:
  = l job.issue_date, format: :long

.small
  b> Актуально до:
  = l job.issue_date + job.valid_time, format: :long

.small
  b> Контактная информация:
  = job.contact

div
  b> Требования:
  - job.skills.each do |skill|
    .label.label-info> = skill